theme: jekyll-theme-minimal

# Site settings
title: "Robinson Arce M"
author: Robinson Arce M
email: arcebq@gmail.com
description: "PhD, Cellular & Molecular Biology | Data Scientist"

# Social links
#github_username: RobinsonArceM
#linkedin: https://www.linkedin.com/in/robinson-arce-molina-4566208b/

# Profile Image 
logo: /assets/profile.jpg
